# Generated by Django 5.2.1 on 2025-05-25 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date_register', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('technical_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_hire', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('printer_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('hours_use', models.IntegerField()),
                ('last_change_nozzle', models.DateField()),
                ('last_maintenance', models.DateField()),
                ('technical_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='api.technical')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_euros', models.FloatField()),
                ('date_register', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.client')),
                ('technical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.technical')),
            ],
        ),
    ]
