# Generated by Django 5.2.1 on 2025-06-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_username_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stl_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_register',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
