# Generated by Django 5.2.1 on 2025-06-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_stl_file_alter_order_date_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(default='blanco', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='material',
            field=models.CharField(default='pla', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='velocity',
            field=models.CharField(default='30', max_length=100),
        ),
    ]
