# Generated by Django 5.2.1 on 2025-06-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_color_order_material_order_velocity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='velocity',
            field=models.DecimalField(decimal_places=0, default=30, max_digits=2),
        ),
    ]
